server:
  port: 8081
#  servlet:
#    context-path: /api 配置统一请求前缀
spring:
  application:
    name: hmdp
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/hmdp?useSSL=false&serverTimezone=UTC
    username: root
    password: 12345678
  redis:
    database: 0
    host: localhost
    port: 6379
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
  servlet:
    multipart:
      max-file-size: 10MB # 文件上传最大大小
mybatis-plus:
  type-aliases-package: com.hmdp.entity # 别名扫描包
# 日志
logging:
  level:
    com.hmdp: debug
