spring:
  redis:
    database: 0 # 选择库
    host: localhost
    port: 6379
    client-type: jedis # 使用lettuce客户端连接
#    lettuce连接配置
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: 1000ms
        min-idle: 0
#    jedis连接配置
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: 1000ms
        min-idle: 0
